version: "3"

services:
  site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: site
    volumes:
      - './:/var/www/html'
    ports:
      - "80:80"

  mysql:
    image: mysql:5.5
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'basebase'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1